class LegacyState < ActiveRecord::Base
  include LegacyBase
  establish_connection "legacy"

  self.table_name = "states"
  # self.primary_key = "old_id"

  # To use autogenerated ids uncomment below
  def dont_migrate_ids
    false
  end

  def migrate_where
    {id: self.id}
  end

  def map
    {
      name: self.name,
      acronym: self.acronym
    }
  end

  def associate
    {
      # association: records.to.associate
    }
  end

end
