require 'open-uri'
class LegacyPressAsset < ActiveRecord::Base

  #def self.name
    #'InMedia'
  #end

  include LegacyBase
  establish_connection "legacy"

  self.table_name = "in_medias"
  # self.primary_key = "old_id"
  image_accessor :image

  # To use autogenerated ids uncomment below
  def dont_migrate_ids
    false
  end

  def migrate_where
    {id: self.id}
  end

  def map
    {
      title: self.title,
      url: self.url,
      remote_image_url: self.image.remote_url(expires: 1.day.from_now)
    }
  end

  def associate
    {
      # association: records.to.associate
    }
  end

end
