class LegacyConfiguration < ActiveRecord::Base
  include LegacyBase
  establish_connection "legacy"

  self.table_name = "configurations"
  # self.primary_key = "old_id"

  # To use autogenerated ids uncomment below
  def dont_migrate_ids
    false
  end

  def migrate_where
    {id: self.id}
  end

  def map
    {
      name: self.name.squish,
      value: self.value.squish
    }
  end

  def associate
    {
      # association: records.to.associate
    }
  end

end
