class LegacyReward < ActiveRecord::Base
  include LegacyBase
  establish_connection "legacy"

  self.table_name = "rewards"
  # self.primary_key = "old_id"

  # To use autogenerated ids uncomment below
  def dont_migrate_ids
    false
  end

  def migrate_where
    {id: self.id}
  end

  def map
    {
      project_id: self.project_id,
      minimum_value: set_minimum_value,
      maximum_backers: self.maximum_backers,
      description: self.description,
      created_at: self.created_at,
      updated_at: self.updated_at,
      row_order: set_minimum_value.to_i,
      show_contact_button: self.show_contact_button,
      soon: self.soon
    }
  end

  def set_minimum_value
    return 10.0 if self.minimum_value < 10.0
    self.minimum_value
  end

  def associate
    {
      # association: records.to.associate
    }
  end

end
