class LegacyProjectDocument < ActiveRecord::Base
  include LegacyBase
  establish_connection "legacy"

  self.table_name = "project_assets"
  # self.primary_key = "old_id"

  image_accessor :asset

  # To use autogenerated ids uncomment below
  def dont_migrate_ids
    false
  end

  def migrate_where
    {id: self.id}
  end

  def map
    {
      remote_document_url: get_document_url,
      project_id: self.project_id,
      created_at: self.created_at,
      updated_at: self.updated_at
    }
  end

  def get_document_url
    self.asset.remote_url(expires: 1.day.from_now)
  end

  def associate
    {
      # association: records.to.associate
    }
  end

end
