class LegacyOauthProvider < ActiveRecord::Base
  include LegacyBase
  establish_connection "legacy"

  self.table_name = "oauth_providers"
  # self.primary_key = "old_id"

  # To use autogenerated ids uncomment below
  def dont_migrate_ids
    false
  end

  def migrate_where
    {id: self.id}
  end

  def map
    {
      name: self.name.downcase,
      key: self.key,
      secret: self.secret,
      scope: get_scope,
      order: self.order,
      strategy: self.strategy,
      path: self.path
    }
  end

  def get_scope
    if self.name.downcase == 'linkedin'
      return 'r_fullprofile r_emailaddress'
    end
    self.scope
  end

  def associate
    {
      # association: records.to.associate
    }
  end

end
